### ISSUE TITLE
Trip planner

### ISSUE THREAD

**Issue by nathanhollows** [wisend/avaunt#45]
The client asked for a new Trip Planner feature.

**Requirements**

_Major features:_

- [x] Save a selection of customers as a "trip" #46 
- [x] Geocode customers #48 
- [ ] Assign a trip to a user
- [x] Reorder the customers within a trip #47 
- [x] A map view to show the ordering #49 
- [ ] Export the whole list as map directions #50 
- [ ] Printable map #51 
- [ ] Schedule the trip (optional) This will automatically display the trip details for everyone #52 

_QOL improvements:_

- [ ] Integrate the trip into the dashboard #56 
- [x] Tidy the main report for note taking #53 
- [x] QR codes in the trip planner print outs #53 
- [x] Remove the two unused/obsolete reports #54 
- [x] Link to directions from the customers page #55
